### PR TITLE
Use built-in instance instead of alias

### PR DESCRIPTION
**Pull request by roman-vynar**
- Use built-in instance instead of alias.
- Join node_ metrics with up{job="mongodb"...} one where needed.
- Some cleanup.

### CODE REVIEW

**Comment by dbmurphy** [comment]
Do we have this code somewhere I can see the dashboards working (like dev pmmdemo?)

**Comment by timvaillancourt** [comment]
This is a great idea @roman-vynar, testing this out locally today

**Comment by timvaillancourt** [comment]
Looks good @roman-vynar, the only issues I spotted were on the "Cluster Summary" dashboard. These graphs break for me on a full sharded cluster:

-CPU % by Shard
-Load Average by Shard
-Memory Usage by Shard

I can see those 3 x graphs were updated for this change so maybe something didn't work here.

The error returned to grafana for all 3 x problem-graphs is:

```
{
  "status": "error",
  "errorType": "bad_data",
  "error": "parse error at char 44: unexpected identifier \"up\" in grouping opts, expected \"(\"",
  "message": "parse error at char 44: unexpected identifier \"up\" in grouping opts, expected \"(\""
}
```

Other than that, this is a great change that makes our Prometheus setup much less complicated 👍

**Comment by roman-vynar** [comment]
prometheus 1.0.1?

**Comment by timvaillancourt** [comment]
0.18.0 😄 , I'll try out 1.0.x. Thanks

**Comment by timvaillancourt** [comment]
Everything is working now on Prometheus 1.x. Can you update the project README.md to mention that is required @roman-vynar? The "Prometheus Configuration" section might need an update for no node_exporter labels too (tells you to add them right now). Looks good to me otherwise 👍

**Comment by roman-vynar** [comment]
I think may be we can merge those dashboards into https://github.com/percona/grafana-dashboards later and made them consistent and not maintaining 2 repos, instructions etc.

**Comment by dbmurphy** [comment]
We should use modules and have a meta repo I think. That way we don't complicate things for non-pmm users who want to use the exporter and dashboard

**Comment by timvaillancourt** [comment]
Good ideas on the repositories, I am happy with either approach 👍

**Comment by timvaillancourt** [comment]
I think this is ready to merge. I want to do some README.md updates so I'll do the doc updates for this PR (in a new PR). @dbmurphy any thoughts?

**Comment by timvaillancourt** [comment]
This was integrated into https://github.com/percona/grafana-dashboards and we're going to point to that. Closing.

**Pull request closed without merging**
